version: '3.8'

services:
    dynamodb:
        container_name: local-dynamodb
        image: amazon/dynamodb-local:latest
        networks:
            - local-dynamodb
        ports:
            - '8000:8000'
        volumes:
            - dynamodata:/home/dynamodblocal
        working_dir: /home/dynamodblocal
        command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'

networks:
    local-dynamodb:
        name: local-dynamodb

volumes:
    dynamodata: {}
