service: lambda--run-dynamodb-local

frameworkVersion: '>=2.3.0'

custom: ${file(./dynamodb/config.yaml)}

provider:
    name: aws
    region: us-east-1
    runtime: nodejs14.x
    lambdaHashingVersion: '20201221'

functions:
    create:
        handler: src/index.create
        events:
            - httpApi:
                  path: /
                  method: post
    getAll:
        handler: src/index.getAll
        events:
            - httpApi:
                  path: /
                  method: get
    getByPk:
        handler: src/index.getByPk
        events:
            - httpApi:
                  path: /{pk}
                  method: get

resources: ${file(./dynamodb/resources.yaml)}

plugins:
    - serverless-offline
    - serverless-plugin-typescript
    - serverless-tscpaths
    - serverless-dynamodb-local
